#include <iostream>
using namespace std;

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

                                        1,2,3,5,8,13,21,34,55,89...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

int main() {

    int sum{2};
    int a{1}, b{2};

    while(b < 4000000) {
            int aux = b;
            b += a;
            a = aux;
            if (b % 2 == 0) sum += b;
    }

    cout << "Sum of Even Fibonacci terms not exceeding four million is: " << sum;

}
